apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: guestbook
  namespace: argocd
spec:
  # How to write back updates to Git
  writeBackConfig:
    method: git
    gitConfig:
      branch: main
      writeBackTarget: "kustomization:apps/guestbook"

  # Select the guestbook application
  applicationRefs:
    - namePattern: "guestbook"
      commonUpdateSettings:
        updateStrategy: latest
      images:
        - alias: guestbook
          imageName: ghcr.io/aungyephyo2215/guestbook
