apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitops-lab
spec:
  project: gitops-lab

  source:
    repoURL: https://github.com/aungyephyo2215/k8s-gitops-lab.git
    targetRevision: main
    path: apps/guestbook

  destination:
    server: https://kubernetes.default.svc
    namespace: app-01

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
