apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 10Gi
    limits.cpu: "6"
    limits.memory: 10Gi
    pods: "100"
